<?php

namespace ContainerVGOpFgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KdXvATgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KdXvATg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KdXvATg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\MyProjectController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\NewProjectController::addProject' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\NewProjectController::joinProject' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegisterController::deconnexion' => ['privates', '.service_locator.91QYP5y', 'get_ServiceLocator_91QYP5yService', true],
            'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegisterController::verification' => ['privates', '.service_locator.91QYP5y', 'get_ServiceLocator_91QYP5yService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MyProjectController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\NewProjectController:addProject' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\NewProjectController:joinProject' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegisterController:deconnexion' => ['privates', '.service_locator.91QYP5y', 'get_ServiceLocator_91QYP5yService', true],
            'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegisterController:verification' => ['privates', '.service_locator.91QYP5y', 'get_ServiceLocator_91QYP5yService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MyProjectController::index' => '?',
            'App\\Controller\\NewProjectController::addProject' => '?',
            'App\\Controller\\NewProjectController::joinProject' => '?',
            'App\\Controller\\RegisterController::deconnexion' => '?',
            'App\\Controller\\RegisterController::register' => '?',
            'App\\Controller\\RegisterController::verification' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MyProjectController:index' => '?',
            'App\\Controller\\NewProjectController:addProject' => '?',
            'App\\Controller\\NewProjectController:joinProject' => '?',
            'App\\Controller\\RegisterController:deconnexion' => '?',
            'App\\Controller\\RegisterController:register' => '?',
            'App\\Controller\\RegisterController:verification' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
