<?php

namespace ContainerVGOpFgd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentLoggerListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_logger_listener' shared service.
     *
     * @return \Symfony\UX\TwigComponent\EventListener\TwigComponentLoggerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'TwigComponentLoggerListener.php';

        return $container->privates['ux.twig_component.component_logger_listener'] = new \Symfony\UX\TwigComponent\EventListener\TwigComponentLoggerListener(($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
