<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVGOpFgd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVGOpFgd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVGOpFgd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVGOpFgd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVGOpFgd\App_KernelDevDebugContainer([
    'container.build_hash' => 'VGOpFgd',
    'container.build_id' => '69deb005',
    'container.build_time' => 1727341630,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVGOpFgd');
