<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::accueil'], [], [['text', '/accueil']], [], [], []],
    'app_my_project' => [[], ['_controller' => 'App\\Controller\\MyProjectController::index'], [], [['text', '/myproject']], [], [], []],
    'app_new_project' => [[], ['_controller' => 'App\\Controller\\NewProjectController::index'], [], [['text', '/newproject']], [], [], []],
    'app_addnew_project' => [[], ['_controller' => 'App\\Controller\\NewProjectController::addProject'], [], [['text', '/addprojetct']], [], [], []],
    'app_join_project' => [[], ['_controller' => 'App\\Controller\\NewProjectController::joinProject'], [], [['text', '/joinproject']], [], [], []],
    'app_proj_dispo' => [[], ['_controller' => 'App\\Controller\\ProjDispoController::accueil'], [], [['text', '/proj']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\RegisterController::login'], [], [['text', '/login']], [], [], []],
    'app_verification' => [[], ['_controller' => 'App\\Controller\\RegisterController::verification'], [], [['text', '/verification']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::register'], [], [['text', '/register']], [], [], []],
    'app_enregistrement' => [[], ['_controller' => 'App\\Controller\\RegisterController::enregistrement'], [], [['text', '/enregistrement']], [], [], []],
    'app_enregistrement_error' => [[], ['_controller' => 'App\\Controller\\RegisterController::enregistrement_error'], [], [['text', '/enregistrement_error']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\RegisterController::deconnexion'], [], [['text', '/deconnexion']], [], [], []],
    'App\Controller\AccueilController::accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::accueil'], [], [['text', '/accueil']], [], [], []],
    'App\Controller\MyProjectController::index' => [[], ['_controller' => 'App\\Controller\\MyProjectController::index'], [], [['text', '/myproject']], [], [], []],
    'App\Controller\NewProjectController::index' => [[], ['_controller' => 'App\\Controller\\NewProjectController::index'], [], [['text', '/newproject']], [], [], []],
    'App\Controller\NewProjectController::addProject' => [[], ['_controller' => 'App\\Controller\\NewProjectController::addProject'], [], [['text', '/addprojetct']], [], [], []],
    'App\Controller\NewProjectController::joinProject' => [[], ['_controller' => 'App\\Controller\\NewProjectController::joinProject'], [], [['text', '/joinproject']], [], [], []],
    'App\Controller\ProjDispoController::accueil' => [[], ['_controller' => 'App\\Controller\\ProjDispoController::accueil'], [], [['text', '/proj']], [], [], []],
    'App\Controller\RegisterController::login' => [[], ['_controller' => 'App\\Controller\\RegisterController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\RegisterController::verification' => [[], ['_controller' => 'App\\Controller\\RegisterController::verification'], [], [['text', '/verification']], [], [], []],
    'App\Controller\RegisterController::register' => [[], ['_controller' => 'App\\Controller\\RegisterController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\RegisterController::enregistrement' => [[], ['_controller' => 'App\\Controller\\RegisterController::enregistrement'], [], [['text', '/enregistrement']], [], [], []],
    'App\Controller\RegisterController::enregistrement_error' => [[], ['_controller' => 'App\\Controller\\RegisterController::enregistrement_error'], [], [['text', '/enregistrement_error']], [], [], []],
    'App\Controller\RegisterController::deconnexion' => [[], ['_controller' => 'App\\Controller\\RegisterController::deconnexion'], [], [['text', '/deconnexion']], [], [], []],
];
